function [sigma,dev_sigma,vol_sigma]=cauchyStress(params,I1bar, ...
                                I2bar,I3, ...
                                I4bar,I5bar, ...
                                base1, ...
                                base2, ...
                                base4, ...
                                base5)
    dPsi.dI1 = diffUdI1(params,I1bar,I2bar,I3,I4bar,I5bar);
    dPsi.dI2 = diffUdI2(params,I1bar,I2bar,I3,I4bar,I5bar);
    dPsi.dI3 = diffUdI3(params,I1bar,I2bar,I3,I4bar,I5bar);
    dPsi.dI4 = diffUdI4(params,I1bar,I2bar,I3,I4bar,I5bar);
    dPsi.dI5 = diffUdI5(params,I1bar,I2bar,I3,I4bar,I5bar);

    fact = 2/I3;
    dev_sigma = fact * (dPsi.dI1 + I1bar * dPsi.dI2) * base1 ...
              - fact * dPsi.dI2 * base2 ...
              + dPsi.dI4 * base4 ...
              + dPsi.dI5 * base5;
    vol_sigma = dPsi.dI3*eye(3);
    sigma = vol_sigma + dev_sigma;
    sigma = real(sigma);

    
end