%% add to path
addpath(genpath(fullfile("functionasRelatedParameters")))
addpath(genpath(fullfile("myOptimizationAlgo")))
addpath(genpath(fullfile("OperationFuncs")))
addpath(genpath(fullfile("usefulFunctions")))
%% load data
clc;
[T,epsMatrix,sigDevMatrix,sigMatrix]=readData();
    
%%
ai = [1;0;0];
sprev = rng(0,'v5uniform');

[I1barList,I2barList, ...
            I3List, ...
            I4barList,I5barList, ...
            Base1List, ...
            Base2List, ...
            Base4List, ...
            Base5List ...
            ] ...
            =get_requiredValues(epsMatrix,ai);

lb = [0.0,0.0,-inf,-inf,-inf,-inf,-inf,-inf,-inf,-inf];
ub = [inf,inf,inf,inf,inf,inf,inf,inf,inf,inf];
objFun = @(params)objective(params,I1barList,I2barList, ...
            I3List, ...
            I4barList,I5barList, ...
            Base1List, ...
            Base2List, ...
            Base4List, ...
            Base5List, ...
            sigMatrix);

options = optimoptions('fmincon', ...
    'StepTolerance', 0, 'ConstraintTolerance', 0, ...
    'Display', 'iter', ...
    'MaxFunctionEvaluations', 10000000, ...
    'MaxIterations',1000);
% initialParams = readmatrix('current_x_min_23.csv');
initialParams = rand(1,4);
[optimalParams, fval] = fmincon(objFun, initialParams, [], [], [], [], lb, ub, [], options);