%%
function optim_algo(filepath,num_params,batch_size)
    %%
    %First define the variables
    [T,epsMatrix,sigDevMatrix,sigMatrix]=readData(filepath);
    
    % modifying the eps matrix
    % factor = 1e-5;
    % epsMatrix(1:425,4:6) = factor*epsMatrix(1:425,4:6) ;
    % epsMatrix(426:918,1:3) = factor*epsMatrix(426:918,1:3) ;
        
    %%
    ai = [1;0;0];
    sprev = rng(0,'v5uniform');
    [I1barList,I2barList, ...
                I3List, ...
                I4barList,I5barList, ...
                Base1List, ...
                Base2List, ...
                Base4List, ...
                Base5List ...
                ] ...
                =get_requiredValues(epsMatrix,ai);
    %%
    batch_size = 300;
    obj = @(params)gradCalculation(params,I1barList, ...
                    I2barList, ...
                    I3List, ...
                    I4barList, ...
                    I5barList, ...
                    Base1List, ...
                    Base2List, ...
                    Base4List, ...
                    Base5List,sigMatrix,batch_size);
    % load("theta.mat");
    theta = rand(1,num_params);
    %%
    % theta = params;
    learning_rate = 1e-4;
    num_iterations = 5e6;
    print_every = 50;
    model_data.title ='$\Psi = c_1 \left(J-1\right)^2 + c_2 \left( \bar{I}_1 -3 \right) + c_3 \left(\bar{I}_4-1\right)+ c_4 \left(\bar{I}_4-1\right)^2 $'; 
    model_data.folder_name = 'model7';
    
    [theta, J_history,theta_best] = adam_optimizer(theta,obj  ...
                                    , learning_rate, ...
                                    num_iterations, ...
                                    print_every,model_data,epsMatrix,sigMatrix);
end