function out1 = diffUdI5_params_1(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%diffUdI5_params_1
%    OUT1 = diffUdI5_params_1(IN1,I_1,I_2,J,I_4alpha,I_5alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-Dec-2023 22:29:25

out1 = 0.0;
end
