function out1 = diffUdI4_params_4(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%diffUdI4_params_4
%    OUT1 = diffUdI4_params_4(IN1,I_1,I_2,J,I_4alpha,I_5alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-Dec-2023 21:38:03

out1 = I_4alpha.*2.0-2.0;
end
