function out1 = diffUdI2_params_3(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%diffUdI2_params_3
%    OUT1 = diffUdI2_params_3(IN1,I_1,I_2,J,I_4alpha,I_5alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-Dec-2023 22:29:24

out1 = 0.0;
end
