function out1 = diffUdI1_params_2(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%diffUdI1_params_2
%    OUT1 = diffUdI1_params_2(IN1,I_1,I_2,J,I_4alpha,I_5alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-Dec-2023 22:29:24

out1 = 1.0;
end
