function out1 = diffUdI3_params_1(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%diffUdI3_params_1
%    OUT1 = diffUdI3_params_1(IN1,I_1,I_2,J,I_4alpha,I_5alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-Dec-2023 21:38:03

params1 = in1(:,1);
out1 = -1.0./params1.^2.*(J.*2.0-2.0);
end
