function sigma=dcauchyDParam(params,I1bar, ...
                                I2bar,I3, ...
                                I4bar,I5bar, ...
                                base1, ...
                                base2, ...
                                base4, ...
                                base5, ...
                                dUdI1_dparam, ...
                                dUdI2_dparam, ...
                                dUdI3_dparam, ...
                                dUdI4_dparam, ...
                                dUdI5_dparam)
    dPsi.dI1 = dUdI1_dparam(params,I1bar,I2bar,I3,I4bar,I5bar);
    dPsi.dI2 = dUdI2_dparam(params,I1bar,I2bar,I3,I4bar,I5bar);
    dPsi.dI3 = dUdI3_dparam(params,I1bar,I2bar,I3,I4bar,I5bar);
    dPsi.dI4 = dUdI4_dparam(params,I1bar,I2bar,I3,I4bar,I5bar);
    dPsi.dI5 = dUdI5_dparam(params,I1bar,I2bar,I3,I4bar,I5bar);

    fact = 2/I3;
    dev_sigma = fact * (dPsi.dI1 + I1bar * dPsi.dI2) * base1 ...
              - fact * dPsi.dI2 * base2 ...
              + dPsi.dI4 * base4 ...
              + dPsi.dI5 * base5;
    vol_sigma = dPsi.dI3*eye(3);
    sigma = vol_sigma + dev_sigma;
end