function derv_U_dI1_dI5 = diffUdI1dI5(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%diffUdI1dI5
%    derv_U_dI1_dI5 = diffUdI1dI5(IN1,I_1,I_2,J,I_4alpha,I_5alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-Dec-2023 21:38:04

derv_U_dI1_dI5 = 0.0;
end
