function derv_U_I1 = diffUdI1(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%diffUdI1
%    derv_U_I1 = diffUdI1(IN1,I_1,I_2,J,I_4alpha,I_5alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-Dec-2023 22:29:26

params2 = in1(:,2);
derv_U_I1 = params2;
end
