function derv_U_dI4_dI4 = diffUdI4dI4(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%diffUdI4dI4
%    derv_U_dI4_dI4 = diffUdI4dI4(IN1,I_1,I_2,J,I_4alpha,I_5alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-Dec-2023 22:29:26

params4 = in1(:,4);
derv_U_dI4_dI4 = params4.*2.0;
end
