function derv_U_dI1_dI1 = diffUdI1dI1(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%diffUdI1dI1
%    derv_U_dI1_dI1 = diffUdI1dI1(IN1,I_1,I_2,J,I_4alpha,I_5alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-Dec-2023 21:38:04

derv_U_dI1_dI1 = 0.0;
end
