function derv_U_dI1_dI4 = diffUdI1dI4(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%diffUdI1dI4
%    derv_U_dI1_dI4 = diffUdI1dI4(IN1,I_1,I_2,J,I_4alpha,I_5alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-Dec-2023 22:29:26

derv_U_dI1_dI4 = 0.0;
end
